### ISSUE TITLE
Add data object to subscribeToPush function

### ISSUE THREAD

**Issue by DHFW** [remix-pwa/push#4]
I would like to also include other data (in my case the userAgent string) as an argument for this function: `export async function subscribeToPush`

If you include this as an optional object, we can extend it how we like. 

So, when I store the subscription in my database when the resource action is called, I can also store the data object (in my case the userAgent string in my `Device` table). That gives some insight what browser the user is using. Thanks.

**Comment by ShafSpecs** [comment]
Sorry for replying *very* late, didn't get a notification from github till this night 😅. That's a good idea, would work on that

**Comment by ShafSpecs** [comment]
Published 👍
